[package]
name = "p2p_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
iyes_loopless = "0.8"
bevy-inspector-egui = "0.13"

[profile.dev.package."*"]
opt-level = 3